### PR TITLE
[PR] Disable university taxonomy archive views

### PR DESCRIPTION
**Pull request by philcable**
This seems like a goofy way to do it, so I'm open to alternatives :).

### CODE REVIEW

**Comment by philcable** [comment]
That was my first thought, too. The URLs still seem work, which threw me off at first, but the content area is indeed blank. This approach does feel better, though :)

**Comment by jeremyfelt** [comment]
Ahh, that could be solved by filtering `query_var` to `false` as well if I remember right.

**Comment by philcable** [comment]
I tried that too, but no dice :). Then I tried setting `publicly_queryable` to `false` in addition to the other two just for fun, but of course that didn't have an impact either.

**Comment by philcable** [comment]
@jeremyfelt I think I'll call this done :). #reviewmerge?

**Pull request merged**
